### ISSUE TITLE
feed.xml links doesn't work 

### ISSUE THREAD

**Issue by lkrzyzanek** [resteasy/resteasy.github.io#52]
The generated https://resteasy.github.io/feed.xml uses  `resteasy.jboss.org` domain which doesn't handle correctly redirects to individual posts e.g. https://resteasy.jboss.org/2020/10/21/run-restful-service-with-bootablejar/

Either make sure correct redirects on `resteasy.jboss.org` or use directly `resteasy.github.io` domain.

**Comment by asoldano** [comment]
@jimma @liweinan , how do you want to fix this?

**Comment by jimma** [comment]
@asoldano  I'll have a look.

**Comment by jimma** [comment]
@lkrzyzanek  Fixed. Thanks for reporting this issue.

**Comment by lkrzyzanek** [comment]
Cool. thanks.
